Keep network policy order as defined
fluxcd/flux2 pull request #1280
Opened 2021-04-15 23:31 UTC by eedorenko

Kustomize by default reorders resources in "legacy" mode. This is harmful for the network policies, as the order of how they are defined in yaml (and applied) matters. At least for Azure Network policy. Different order leads to different resulting iptables.

This is a simple fix to suppress the default Kustomize reordering for network policies while building the manifests.

Fixes #703

2021-04-16 05:43 UTC, stefanprodan requested changes
Can you please rename the file and the object to “allow-egress”

2021-04-16 16:48 UTC, eedorenko commented
> Can you please rename the file and the object to “allow-egress”

Done

2021-04-19 13:14 UTC, stefanprodan commented
@eedorenko please rebase with upstream main, squash all commits into one and force push.

2021-04-20 07:13 UTC, stefanprodan approved these changes
LGTM 

Thanks @eedorenko

2021-04-20 07:13 UTC, merged