Fix flux install command so it returns an error when unexpected arguments are passed
fluxcd/flux2 pull request #4404
Opened 2023-11-15 01:33 UTC by VinGarcia

This PR was implemented to address the issue reported by myself on #4403.

2023-11-15 01:36 UTC, VinGarcia commented on cmd/flux/install.go
> +  flux install --export | kubectl apply --dry-run=client -f-
```suggestion
  flux install --export | kubectl apply --dry-run=client -f- 
```

2023-11-15 07:19 UTC, makkes requested changes
There's a much simpler solution here by using the `Args` field of `Command`:

```go
var installCmd = &cobra.Command{
	Args: cobra.NoArgs,
```

2023-11-16 21:37 UTC, VinGarcia commented
@makkes just implemented your suggestion, thanks =]

2023-11-17 06:24 UTC, stefanprodan commented
@VinGarcia can you please squash all commits into one and rebase.

2023-11-17 07:30 UTC, makkes commented on cmd/flux/install_test.go
> +			name:   "invalid namespace",
```suggestion
			name:   "invalid sub-command",
```

2023-11-17 13:55 UTC, VinGarcia commented
@stefanprodan and @makkes just squashed the commits, it should be ready now.

2023-11-17 13:57 UTC, makkes approved these changes

2023-11-17 13:59 UTC, makkes commented
One thing that bothers me a little here is that this PR only fixes this for the `install` command but all the others stay the same. Running `flux check foobar` still succeeds while `flux install foobar` fails. I personally would like to strive for consistency here. @stefanprodan wdyt?

2023-11-17 15:37 UTC, VinGarcia commented
@makkes I could add these changes on either this PR on a separate one. I would just need the list of commands on which to do it.

2023-11-21 14:37 UTC, VinGarcia commented
@makkes and @stefanprodan how should we proceed?

2023-11-21 14:40 UTC, makkes commented
Let's add a proper `Args` setting to each command.

2023-11-21 15:03 UTC, VinGarcia commented
@makkes I started going over all instances of `cobra.Command` and checking `flux [command] --help` for each of them, the ones with no args I will add `Args: cobra.NoArgs`, but some of them like `cmd/flux/bootstrap_bitbucket_server.go` do not have unit tests, so I have three options:

1. Not add unit tests at all
2. Only add tests to the files that already have unit tests
3. Write unit tests for all files even the ones that don't have `_test.go` files already.

The last option might be hard for me, and I don't know how much important you guys think 2. is.

2023-11-23 11:30 UTC, makkes commented
There is a certain chance that adding the wrong PositionalArgs to a command would result in the command not being usable, anymore, e.g. when adding `cobra.NoArgs` to the `get ks` command. I suggest it is desirable writing a unit test that verifies this doesn't happen.

I agree with Stefan that adding PositionalArgs to each command should be made in a subsequent PR and we keep this one focussed on what's said in the title.

2023-11-23 11:31 UTC, makkes approved these changes

2023-11-27 17:19 UTC, merged

2023-11-27 17:19 UTC, makkes commented
Thanks @VinGarcia! 🤜🏻🤛🏻